Moved the example configuration files to doc/examples. The configuration file in conf/ are the default ones that will be installed. Created startup scripts and sysconfig templates for the transcoder admin, manager and worker in conf/redhat.
svn path=/flumotion-advanced/flumotion-transcoder/trunk/; revision=8321

diff --git a/conf/redhat/flumotion-transcoder-worker b/conf/redhat/flumotion-transcoder-worker
--- a/conf/redhat/flumotion-transcoder-worker
+++ b/conf/redhat/flumotion-transcoder-worker
@@ -1,10 +1,10 @@
 #!/bin/bash
 #
-# Startup script for Flumotion Transcoder
+# Startup script for Flumotion Transcoder Worker
 #
-# flumotion-transcoder: Flumotion Transcoder daemon
+# flumotion-transcoder-worker: Flumotion Transcoder Worker Daemon
 #
-# chkconfig: - 75 25
+# chkconfig: - 76 24
 #
 # description: Flumotion is a streaming server for audio and video. \
 #              See http://www.fluendo.com for details.
@@ -13,35 +13,41 @@
 . /etc/rc.d/init.d/functions
 
 # paths to files and variables
-service=flumotion-transcoder
-shortservice=transcoder
-prog=/usr/sbin/$service
+service=flumotion-transcoder-worker
+shortservice=transcoder-worker
+prog=/usr/bin/flumotion-worker
 lockdir=/var/lock/subsys
 lockfile=${lockdir}/$service.lock
-pidfile=/var/run/flumotion/$shortservice.pid
-logfile=/var/log/flumotion/$shortservice.log
+filebasename=worker-$(hostname)
+pidfile=/var/run/flumotion/$filebasename.pid
+logfile=/var/log/flumotion/$filebasename.log
 sysconfig=/etc/sysconfig/$service
 
 # source configuration
 if [ -f $sysconfig ] ; then
-        . $sysconfig
+	. $sysconfig
 fi
 
 # to make sure our service log file is always owned by the correct user,
 # we touch it
 touch_logfile() {
-        touch $logfile
-        chown flumotion $logfile
+	touch $logfile
+	chown flumotion $logfile
 }
 
 # if arguments are specified, we only start/stop that service part
 start() {
 	touch_logfile
-
 	echo -n $"Starting $service: "
-        # OPTIONS can be set from the config file as well
-
-	daemon --user flumotion $prog --daemon $OPTIONS /etc/flumotion-transcoder.ini
+		# MANAGER_HOST, MANAGER_PORT, AUTH_USERNAME and AUTH_PASSWORD \
+		# can be overriden from the config file
+		# OPTIONS can be set from the config file as well
+	daemon --user flumotion $prog -D -P 7632 -n $(hostname) \
+							-H ${MANAGER_HOST:-"localhost"} \
+							-P ${MANAGER_PORT:-"7632"} \
+							-u ${AUTH_USERNAME:-"user"} \
+							-p ${AUTH_PASSWORD:-"test"} \
+							$OPTIONS
 	RETVAL=$?
 	echo
 	[ $RETVAL = 0 ] && touch ${lockfile}
@@ -49,11 +55,10 @@ start() {
 }
 
 stop() {
-        RETVAL=0
-	if test -e ${lockfile}
-	then
+	RETVAL=0
+	if test -e ${lockfile}; then
 		echo -n $"Stopping $service: "
-                # killproc will show success or failure, but not echo newline
+			# killproc will show success or failure, but not echo newline
 		killproc -p $pidfile $service
 		RETVAL=$?
 		echo
@@ -83,25 +88,25 @@ status() {
 
 # See how we were called.
 case "$1" in
-  start)
-	shift
-	start $*
-	;;
-  stop)
-	shift
-	stop $*
-	;;
-  restart)
-	shift
-	stop $*
-	start $*
-	;;
-  status)
-        status $*
-	;;
-  *)
-	echo $"Usage: $service {start|stop|restart|status}"
-	exit 1
+	start)
+		shift
+		start $*
+		;;
+	stop)
+		shift
+		stop $*
+		;;
+	restart)
+		shift
+		stop $*
+		start $*
+		;;
+	status)
+		status $*
+		;;
+	*)
+		echo $"Usage: $service {start|stop|restart|status}"
+		exit 1
 esac
 
 exit $RETVAL
